=== DRJacome/FP-DAW/1º curso/LMSXI/3º trimestre/T6/Tareas/rodriguez_jacome_david_DAW1_tarefa6.6/B/hardware.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Hardware (Maquina*)>
  <!ELEMENT Maquina (Info, Config, Notas?)>
    <!ELEMENT Info (Espazo, Tipo, Fabricante, Procesador?, Memoria?, Disco*, (Lectora | Gravadora)?)>
      <!ELEMENT Espazo (nome, tipo, ubicación)>
        <!ELEMENT nome (#PCDATA)>
        <!ELEMENT tipo (aula, sala, departamento)>
          <!ELEMENT aula (#PCDATA)>
          <!ELEMENT sala (#PCDATA)>
          <!ELEMENT departamento (#PCDATA)>
        <!ELEMENT ubicación (#PCDATA)>
        <!ATTLIST Espazo
          idEspazo ID #REQUIRED>
      <!ELEMENT Tipo (#PCDATA)>
      <!ELEMENT Fabricante (nomeF, Web, correo)>
        <!ELEMENT nomeF (#PCDATA)>
        <!ELEMENT Web (#PCDATA)>
        <!ELEMENT correo (#PCDATA)>
        <!ATTLIST Fabricante
          idFabricante ID #REQUIRED>
      <!ELEMENT Procesador (#PCDATA)>
      <!ELEMENT Memoria (#PCDATA)>
      <!ELEMENT Disco EMPTY>
      <!ELEMENT Lectora (#PCDATA)>
      <!ELEMENT Gravadora (#PCDATA)>
    <!ELEMENT Config (Role*, OS?, IP*, Gateway?)>
      <!ELEMENT Role (#PCDATA)>
      <!ELEMENT OS (#PCDATA)>
      <!ELEMENT IP (#PCDATA)>
      <!ELEMENT Gateway (#PCDATA)>
    <!ELEMENT Notas (#PCDATA)>
  <!ENTITY % Unidade_optica
    "Tipo (CD | DVD | BD) #REQUIRED
    Velocidade CDATA #IMPLIED">
    <!ATTLIST Maquina
      Nome ID #REQUIRED
      Fabricante IDREF #REQUIRED
      Espazo IDREF #REQUIRED>
      <!ATTLIST Procesador
        Marca (Intel | AMD) #REQUIRED
        NumNucleos CDATA "1"
        Velocidade CDATA #IMPLIED>
      <!ATTLIST Disco
        Tecnoloxía (ATA | SATA | SCSI | SSD) #IMPLIED
        Capacidade CDATA #REQUIRED>
      <!ATTLIST Memoria
        Tecnoloxía (DDR | DDR2 | DDR3) #IMPLIED>
      <!ATTLIST Lectora %Unidade_optica; >
      <!ATTLIST Gravadora %Unidade_optica; >

=== DRJacome/FP-DAW/1º curso/LMSXI/3º trimestre/T6/Práctica DTD/6_6/B/rodriguez_jacome_david_DAW1_tarefa6_6b.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Hardware SYSTEM "hardware.dtd">
<Hardware>
  <Maquina Nome="OrdenadorLG" Fabricante="LG36" Espazo="S25">
    <Info>
      <Espazo idEspazo="S25">
        <nome>Informática</nome>
        <tipo>
          <aula>25</aula>
          <sala>Esquerda</sala>
          <departamento>Informática</departamento>
        </tipo>
        <ubicación>Universidade ala esquerda</ubicación>
      </Espazo>
      <Tipo>Ordenador</Tipo>
      <Fabricante idFabricante="LG36">
        <nomeF>LG</nomeF>
        <Web>www.lg.com</Web>
        <correo>empresalg@gmail.com</correo>
      </Fabricante>
      <Procesador Marca="Intel">i5</Procesador>
      <Memoria Tecnoloxía="DDR2">16</Memoria>
      <Disco Tecnoloxía="SSD" Capacidade="240"/>
    </Info>
    <Config>
      <OS>Windows</OS>
    </Config>
  </Maquina>
</Hardware>
