<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE mensaxe [
<!ELEMENT mensaxe (de, para+, asunto, adxunto*) >
    <!ATTLIST mensaxe
      prioridade (baixa | normal | urxente) "normal"
      gardarBandexa CDATA "Enviados">
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT corpo (#PCDATA)>
<!ELEMENT adxunto (#PCDATA)>
]>

<mensaxe prioridade = "urxente">
    <de>maria@gmail.com</de>
    <para>ignacio@gmail.com</para>
    <para>pedro@edu.xunta.es</para>
    <asunto>Envíoche os arquivos</asunto>
    <adxunto>D:\fotos\dePesca.jpg</adxunto>
    <adxunto>D:\docs\carta.odt</adxunto>
    <adxunto>D:\fotos\naCea.jpg</adxunto>
</mensaxe>